{{- if .Values.realtime.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.realtime.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.realtime.environment) . | nindent 2 }}
{{- end }}
