{{- if .Values.db.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.db.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.db.name" $ }}
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.db.environment }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "supabase.db.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "helicone.name" . }}-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helicone.name" . }}-postgres
                  key: POSTGRES_PASSWORD
            - name: PGPASSWORD
              value: $(POSTGRES_PASSWORD)
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/00000000000004_logs.sql
              name: helicone-migrations
              subPath: 00000000000004_logs.sql
            - mountPath: /docker-entrypoint-initdb.d/migrations/20230306081039_realtime.sql
              name: helicone-migrations
              subPath: 20230306081039_realtime.sql
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/00000000000006_roles.sql
              name: helicone-migrations
              subPath: 00000000000006_roles.sql
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/00000000000005_webhooks.sql
              name: helicone-migrations
              subPath: 00000000000005_webhooks.sql
            {{- with .Values.db.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.db.persistence.enabled }}
            - mountPath: {{ .Values.db.persistence.mountPath }}
              name: postgres-volume
              subPath: {{ .Values.db.persistence.subPath }}
            {{- end }}
          {{- with .Values.db.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: helicone-migrations
          configMap:
            name: {{ include "supabase.db.fullname" . }}-helicone-migrations
        {{- with .Values.db.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.db.persistence.enabled }}
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: {{ include "supabase.db.fullname" . }}-pvc
        {{- end }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
