{{- if .Values.db.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "supabase.db.fullname" . }}-pvc
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  {{- with .Values.db.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.db.persistence.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}


