{{- if .Values.rest.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.rest.environment) . | nindent 2 }}
{{- end }}
