apiVersion: v1
kind: Service
metadata:
  name: {{ include "helicone.worker.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helicone.worker.service.type }}
  ports:
    - port: {{ .Values.helicone.worker.service.port }}
      targetPort: 8787
      protocol: TCP
      name: http
  selector:
    {{- include "helicone.worker.selectorLabels" . | nindent 4 }}
