{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.auth.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.auth.environment) . | nindent 2 }}
{{- end }}
