{{- if .Values.storage.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.storage.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.storage.environment) . | nindent 2 }}
{{- end }}
