{{- if .Values.meta.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.meta.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.meta.environment) . | nindent 2 }}
{{- end }}
