{{- if .Values.kong.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kong.service.type }}
  ports:
    - name: http
      port: {{ .Values.kong.service.httpPort }}
      targetPort: 8000
      protocol: TCP
    - name: https
      port: {{ .Values.kong.service.httpsPort }}
      targetPort: 8443
      protocol: TCP
  selector:
    {{- include "supabase.kong.selectorLabels" . | nindent 4 }}
{{- end }}
