{{- if .Values.kong.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: {{ include "supabase.kong.fullname" . }}-{{ .Values.Namespace }}-mapping
      host: {{ .Values.kong.ingress.host }}
      prefix: /
      ambassador_id: ambassador-private
      service: {{ include "supabase.kong.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.kong.ingress.port }}
      timeout_ms: 100000
spec:
  type: {{ .Values.kong.service.type }}
  ports:
    - name: http
      port: {{ .Values.kong.service.httpPort }}
      targetPort: 8000
      protocol: TCP
    - name: https
      port: {{ .Values.kong.service.httpsPort }}
      targetPort: 8443
      protocol: TCP
  selector:
    {{- include "supabase.kong.selectorLabels" . | nindent 4 }}
{{- end }}
