apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helicone.web.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.helicone.web.environment) . | nindent 2 }}
