apiVersion: v1
kind: Service
metadata:
  name: {{ include "helicone.web.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helicone.web.service.type }}
  ports:
    - port: {{ .Values.helicone.web.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "helicone.web.selectorLabels" . | nindent 4 }}
