{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.functions.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
data:
  {{- tpl (toYaml .Values.functions.environment) . | nindent 2 }}
{{- end }}
