apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - port: {{ .Values.clickhouse.service.port }}
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}