apiVersion: v1
kind: Service
metadata:
  name: {{ include "helicone.clickhouse.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helicone.clickhouse.service.type }}
  ports:
    - port: {{ .Values.helicone.clickhouse.service.port }}
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    {{- include "helicone.clickhouse.selectorLabels" . | nindent 4 }}